### PR TITLE
Support node 4.x

### PR DESCRIPTION
**Pull request by robcolburn**
Bumps `weak` to `1.0.0`, which requires our tests to use `npm>=1.4`.  Technically, this is considered an optional dependency for our dependents, so it should fail gracefully if they are using an earlier version of npm.

Further, adds some build-chain rebuilding for linux required by `nan`, a dependency of `weak`.

Fixes https://github.com/substack/dnode/issues/171

Replaces https://github.com/substack/dnode/pull/172 & https://github.com/substack/dnode/pull/173

### CODE REVIEW

**Comment by apsavin** [comment]
Thanks, Rob!

**Comment by mxk1235** [comment]
thanks!

**Comment by robcolburn** [comment]
:dancer: Thanks for the merge! :)

**Comment by mxk1235** [comment]
can you do a quick 'npm publish' for this version too?

**Comment by seethroughtrees** [comment]
just published.  thanks for the update!

**Comment by robcolburn** [comment]
Hooray! My modules that test on `phantom` are passing in node 4 :)

**Comment by seethroughtrees** [comment]
Nice!  :+1:

**Comment by wizardzloy** [comment]
great @robcolburn, thx for organizing everything!

**Pull request merged**
