### PR TITLE
Upgrade version of "weak" dependency

### PR DESCRIPTION
**Pull request by wizardzloy**
Fixes https://github.com/substack/dnode/issues/171

### CODE REVIEW

**Comment by apsavin** [comment]
It seems that this change breaks dnode on node 0.8 and 0.10.
By the way, I think, it would be nice to change travis options to run tests on node 4.0 as well.

**Comment by wizardzloy** [comment]
@apsavin it's true, but looks like we cannot have it working on both <=0.10 and >=4.0

**Comment by hnrch02** [comment]
:+1:

**Comment by mxk1235** [comment]
would really love this patch.  do you have to make a branch just for v4.0.0?

**Comment by silentroach** [comment]
+1

**Comment by robcolburn** [comment]
@wizardzloy / @substack,
Sometimes I feel like I understand `npm`… sometimes.  From what I understand, `npm` maintains a single "master" version.

Could we do something, create a git branch `pre-4`, and use that to publish a dummy version `1.2.1` to `npm` with a slightly updated engine directive:

```json
  "engine" : {
    "node" : ">=0.6.0 <4.0.0"
  }
```

Then on `master` branch update the engine directive and publish another version `2.0.0`

```json
  "engine" : {
    "node" : ">=4.0.0"
  }
  "dependencies": {
    "weak": "1.0.0"
  }
```

---
I mean that or we try to convince `weak` to support both >4 in current version.

**Comment by robcolburn** [comment]
@wizardzloy,
Hey it looks like is actually a `npm` issue that is resolved by bumping `npm` version. Apparently, `nvm` defaults `node v0.8` to using `npm 1.2`, however that version breaks on dependencies specified with a `^`.  This PR, and the `weak` module itself uses the `^` to specify dependencies, so we need to bump to a newer version of `npm`.  Fortunately, `npm 1.4` supports `^`.  So, we should follow `weak`'s example and bump the `npm` version.

https://github.com/TooTallNate/node-weak/blob/master/.travis.yml#L21-L26

New PR here: https://github.com/substack/dnode/pull/174

**Pull request closed without merging**
