### PR TITLE
Updated travis

### PR DESCRIPTION
**Pull request by seethroughtrees**
Add later versions of node for travis ci

### CODE REVIEW

**Comment by apsavin** [comment]
Cool, let's merge it)

**Comment by seethroughtrees** [comment]
Done.  are we able to bump version and push to npm?  @apsavin

**Comment by apsavin** [comment]
I think, yes, why not. Let's publish 1.2.1.

**Comment by seethroughtrees** [comment]
@apsavin  Bumped version, getting:

```npm ERR! "You cannot publish over the previously published version 1.2.0." : dnode``` 

on npm publish dnode.  any thoughts?

**Comment by seethroughtrees** [comment]
ahh, nevermind.  think i got it ;)

**Pull request merged**
