### PR TITLE
Upgraded weak dep

### PR DESCRIPTION
**Pull request by seethroughtrees**
Updated dependency to address iojs 2 and node 0.12 issue.

Tests pass.

https://github.com/substack/dnode/issues/161

### CODE REVIEW

**Comment by seethroughtrees** [comment]
@substack okay for me to merge this and close the issue?  It'll still need a version bump and push to npm though.

i can review some of the PRs as well, if you like.

**Comment by apsavin** [comment]
@seethroughtrees as I understand, @substack don't mind.
I think, you can merge this.
Also, it would be great if you review others PR's and merge some. I think, we can merge #162, #130 at least and then publish a new version. Also, I think, we can just close #146.

**Comment by seethroughtrees** [comment]
Agreed,  @apsavin  

I'm out of commission today, but will help look over those PR's very soon.

**Comment by seethroughtrees** [comment]
@apsavin - agreed on https://github.com/substack/dnode/pull/130 and https://github.com/substack/dnode/pull/146.  

https://github.com/substack/dnode/pull/162 will cause a conflict as it updated to 0.4.0.  I'll just create an issue and make a new PR.

**Comment by apsavin** [comment]
@seethroughtrees I think you can do the change without an extra issue, just create an PR.

**Comment by seethroughtrees** [comment]
Cool.

**Pull request merged**
